version: '2'
services:
  trexsampleapplication-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/trexSampleApplication/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=trexSampleApplication
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
